### ISSUE TITLE
If there is an active region, turn on vim-region-mode will get error.

### ISSUE THREAD

**Issue by jinzhu** [ongaeshi/emacs-vim-region#1]
When there is an active region already, and you turn on vim-region,
the current region will be cleared, but vim-region hotkey still works.

I think this doesn't works as expected, maybe change to below works better?

If current region is not opened by vim-region, doesn't clear the region, and active all hotkeys.

If current region is opened by vim-region, keep the behavior like now. (only disable hotkeys)

Any ideas?

**Comment by ongaeshi** [comment]
Not clear region when there is an active region already. ddab711
Thanks.

**Comment by jinzhu** [comment]
Thank you for your update. ;)

But I think it is still not perfect because of even the region is kept, but still not possible to use any shortcuts, any of them will kill the region also.

**Comment by jinzhu** [comment]
Seems the issue is caused by I have cua-mode enabled.

**Comment by ongaeshi** [comment]
I am also using the cua-mode but it seems to move. It is my init.el.

``` lisp
(cua-mode t)
(setq cua-enable-cua-keys nil)
```

A problem is happening or will be cua-set-rectangle-mark(C-RET)?
cua-mode bind your own key, and vim-region support is maybe difficult.
