### ISSUE TITLE
Doesn't compatible with multiple-cursors, rectangle...

### ISSUE THREAD

**Issue by jinzhu** [ongaeshi/emacs-vim-region#2]
When using multiple-cursors, rectangle to do some editing, the region will disappear. But vim-region's hot keys still works.

Maybe it is better to do it like this?

If type any hotkeys that vim-region doesn't support, then leave the vim-region mode  (unless in eternal mode) but keep the region.

After this I think vim-region should be able to works well with multiple-cursors and rectangle...

Any ideas?

**Comment by ongaeshi** [comment]
I wanted to do so, but I don't know to detect non support hotkeys from emacs's minor mode...
I'll try to check  to detect non support hotkeys.

**Comment by jinzhu** [comment]
Is there any region disappear hooks could be used to do this?

Or maybe possible to check if easy-kill has some codes related to this?

Sorry, I am on mobile, can't give you some helpful suggestions
2013-11-26 下午4:32于 "ongaeshi" notifications@github.com写道：

**Comment by jinzhu** [comment]
This could be done with pre-command-hook, here is an example

 https://code.google.com/p/ejumplist/source/browse/trunk/jumplist.el#161

**Comment by ongaeshi** [comment]
Fix at 4c6db63. Thanks good information!

**Comment by jinzhu** [comment]
Looks good, thank you
